### ISSUE TITLE
Scheduling with mailgen

### ISSUE THREAD

**Issue by ayoola-solomon** [eladnava/mailgen#13]
Are you thinking of adding scheduling to this module any time soon or do you want me to create a pull request?. It will come in handy

**Comment by eladnava** [comment]
Hi @ayoola-solomon!

What do you mean by scheduling? Scheduling e-mails to be sent in the future?

If so, that is not really the point of Mailgen -- since it doesn't actually send the e-mails, it only generates their HTML/textual content for you.

**Comment by ayoola-solomon** [comment]
Yes I meant Scheduling e-mails to be sent in the future?

**Comment by eladnava** [comment]
That is not really the point of Mailgen -- since it doesn't actually send the e-mails, it only generates their HTML/textual content for you.

**Comment by ayoola-solomon** [comment]
My bad... Thanks for the prompt response. Hopefully the module can evolve into doing that in the future.

**Comment by eladnava** [comment]
@ayoola-solomon Might want to check out [node-schedule](https://github.com/node-schedule/node-schedule) in conjunction with [nodemailer](https://github.com/nodemailer/nodemailer) to achieve scheduled e-mail.
