### ISSUE TITLE
Threading Emails

### ISSUE THREAD

**Issue by harmonicradius** [eladnava/mailgen#17]
I would like to send emails that are part of an existing thread. I'm using mailgen to generate them, and mailgun to send the emails. Is it possible to use X-Entity-Ref-ID to let these emails know that they are all part of a single thread?

Thanks!

**Comment by eladnava** [comment]
Hi @harmonicradius,
If you simply don't supply the X-Entity-Ref-ID header, Gmail / Inbox will automatically group your e-mails based on smart logic (i.e. same or similar subject / content for those e-mails).

Give it a shot and let me know! =)

**Comment by harmonicradius** [comment]
Thanks for the quick reply.

I have sent several emails with the same subject line, but they don't group by default (perhaps in gmail, but not in live mail). 

Mailgun says there is a way to use message ids to have them group (ref: http://blog.mailgun.com/tracking-replies-in-mailgun-or-any-other-email/)

^ I'm not sure what the easiest way to accomplish this is though..

**Comment by eladnava** [comment]
Based on that article, it looks like simply sending the `Message-ID` header with your e-mails (and using the exact same message ID for all e-mails you want grouped) should suffice?

They went for something like this:
`Message-ID: <123456@samples.mailgun.org>`

**Comment by eladnava** [comment]
Closing this due to lack of response. Please feel free to reply if you are still having trouble.
