### ISSUE TITLE
Normalize line breaks in plaintext versions of generated e-mails

### ISSUE THREAD

**Issue by eladnava** [eladnava/mailgen#19]
Currently, when calling `mailgen.generatePlaintext(email)`, the string returned looks something like this:

```
Hi John,
Welcome to Mailgen! We’re very excited to have you on board.



To get started with Mailgen, please click here:
https://mailgen.js/confirm?s=d9729feb74992cc3482b350163a1a010
To read our frequently asked questions, please click here:
https://mailgen.js/faq




Need help, or have questions? Just reply to this email, we\'d love to help.

Yours truly,
Mailgen
```

The line-breaks are either excessive or missing. What I think we should do instead is ignore  `\n` line breaks in the `index.txt` theme files and instead have each theme indicate a line break by a `<br />` tag, even though the plaintext version isn't supposed to have any HTML. Mailgen will replace all `<br />` tags with a `\n` line break.

This would be a breaking change, but I'm thinking of running this replace logic only if the current theme's plaintext file contains at least one `<br />`, to avoid this being a breaking change.

**Comment by vuchl** [comment]
On it!

**Comment by eladnava** [comment]
This is up for grabs again, unless @vuchl wants to give it another shot.

**Comment by vuchl** [comment]
Hey @eladnava!

I think i got what you mean: strip all `\n`s, andd replace `<br />`s in the rendered text. If you aggree I'd love to implement that in the second try.

**Comment by eladnava** [comment]
Yes, that's basically what needs to be done. Also, every theme's `index.txt` needs to be updated to include `<br />` characters in the relevant places where we intend line-breaks.

Please run the scripts in `examples/` using `mailgen.generatePlaintext()`, the output should be similar to this in regards to the line breaks:

```
Hi John,
Welcome to Mailgen! We’re very excited to have you on board.

To get started with Mailgen, please click here:
https://mailgen.js/confirm?s=d9729feb74992cc3482b350163a1a010

To read our frequently asked questions, please click here:
https://mailgen.js/faq

Need help, or have questions? Just reply to this email, we\'d love to help.

Yours truly,
Mailgen
```

**Comment by vuchl** [comment]
Wouldnt it be rather
```html
Hi John,<br />Welcome to Mailgen! We’re very excited to have you on board.<br /><br />To get started with Mailgen, please click here:<br />https://mailgen.js/confirm?s=d9729feb74992cc3482b350163a1a010<br /><br />To read our frequently asked questions, please click here:<br />https://mailgen.js/faq<br /><br/>Need help, or have questions? Just reply to this email, we\'d love to help.<br /><br />Yours truly,<br />Mailgen
```

**Comment by eladnava** [comment]
Nope. We want `generatePlaintext()` to return **plaintext**. The themes' `index.txt` files are the ones that will contain `<br />` to signal to Mailgen where a line-break should appear. Right now we simply copy the `index.txt` as is (with its `\n` line breaks) and return it in `generatePlaintext()` (after evaluating the `ejs` statements), which leads to excessive line breaking since the statements themselves take up lines as well.

I know this may be confusing, but I hope you understand it now. Not sure if I can make it any clearer.

**Comment by vuchl** [comment]
Ah now i get what you are trying to tell me. basically I change the templates at first and then implement the replacing so that the template is dumped as you posted. :thinking:

**Comment by eladnava** [comment]
Yes, I think you got it now. 😄

**Comment by vuchl** [comment]
Well maybe now #22

**Comment by eladnava** [comment]
Closed via #22.

**Comment by vuchl** [comment]
Finally :grin:

**Comment by eladnava** [comment]
Thanks so much for your patience and awesome job! 😄

**Comment by vuchl** [comment]
Was a great experience for a git and js pleb like me. But you are still right with the concerns regarding the performance.
