### ISSUE TITLE
Copyable link was removed

### ISSUE THREAD

**Issue by Pinpickle** [eladnava/mailgen#26]
1944ccb4 removed the plain text version of action links that could be copied and pasted into browsers.

As #16 demonstrates that the button is invisible on Outlook, it really does make sense to have this as a fallback.

I was wondering why it was removed?

**Comment by eladnava** [comment]
Hi @Pinpickle,
The plaintext link was removed for i18n (translation) purposes as mentioned in #24. Also, it is only present in the default theme which was an inconsistency.

If the button is invisible in Outlook in the default theme, the solution would be to fix that bug in Outlook by modifying the theme's styling / markup.

If you have access to Outlook, could you by any chance try to fix the button and possibly submit a PR?

**Comment by eladnava** [comment]
Please continue this in #16.
