### ISSUE TITLE
When i put an svg in logo, nor the logo neither the name is shown.

### ISSUE THREAD

**Issue by danielCommitted** [eladnava/mailgen#27]

**Comment by eladnava** [comment]
Hi @danielCommitted,
Thanks so much for taking the time to report this bug.

Can you please post example code (i.e. the constructor code that you use to initialize Mailgen with an SVG logo?)

**Comment by danielCommitted** [comment]
`new Mailgen({
  theme: 'default',
  textDirection: 'ltr',
  product: {
    // Appears in header & footer of e-mails
    name: {name},
    link: {link},
    logo: 'https://daks2k3a4ib2z.cloudfront.net/5661f2003837fdb102819aa7/596e100d68dd86705eb704d7_CLOUDWITHME_LOGO.svg',
    copyright: {copyright}
  }
});`

**Comment by eladnava** [comment]
Hi @danielCommitted,
Upon inserting the `svg` link in the `logo` option, the following was generated:

![screen shot 2017-12-09 at 6 46 56 pm](https://user-images.githubusercontent.com/4394189/33794143-6a3f40ac-dd11-11e7-9e9c-5daa6df24323.png)

When using the `logo` option, mails will no longer contain the `name` in the headers, but only in footers within the copyright.

Is it possible that the `svg` logo isn't being displayed in e-mails only, but `mailgen` is able to generate an e-mail that looks proper within Chrome?

**Comment by eladnava** [comment]
Closing due to lack of response, feel free to reopen if you still need help with this.
