### ISSUE TITLE
Ability to add Logo to email header and footer

### ISSUE THREAD

**Issue by sudeshgutta** [eladnava/mailgen#30]
It would be great if we had an option to add an image along with text content as part of name property, so that we can have logo as part of header and footer 

Currently only text content are allowed as part of header and footer 

_Expected Config Example:_
```
const mailGenerator = new Mailgen( {
  theme: "default",
  product: {
      name: "NAME",
      image: "LOGO.png"
  }
} );
```

Thanks!

**Comment by sudeshgutta** [comment]
Just saw that it can be configured and It would be great if this config was documented

**Comment by eladnava** [comment]
Hi @sudeshgutta!

Thanks for your suggestion, however, the `logo` parameter is documented in the [Usage](https://github.com/eladnava/mailgen#usage) section already as `Optional product logo`:
```
// Configure mailgen by setting a theme and your product info
var mailGenerator = new Mailgen({
    theme: 'default',
    product: {
        // Appears in header & footer of e-mails
        name: 'Mailgen',
        link: 'https://mailgen.js/'
        // Optional product logo
        // logo: 'https://mailgen.js/img/logo.png'
    }
});
```
