### ISSUE TITLE
How can we add multi tables into a email?

### ISSUE THREAD

**Issue by Sunnykaby** [eladnava/mailgen#32]
As the title, I want to add two tables into one email. How can i do?

**Comment by eladnava** [comment]
Hi @Sunnykaby,
At this time `mailgen` does not support this scenario. The `table` param only accepts an object:
https://github.com/eladnava/mailgen/tree/59f730560090bb014b9000dc017bf6977004fd1e#table

If you're feeling up to it, you can modify `mailgen` to accept both a `object` and an `array` of `object` for the `table` param, and modify the `mailgen` built-in templates to support multiple tables. Would you like to give it a shot?

**Comment by Sunnykaby** [comment]
maybe I can have a try. Let me digging your project first. 
And I have another question. I can't open the html email with the really html format on Outlook, or some famous Email client.

**Comment by eladnava** [comment]
Closing due to lack of response/demand.

**Comment by eladnava** [comment]
@labzy88 Thanks so much for your work on this amazing PR! 🎉 

Just merged and applied some CSS styling changes in https://github.com/eladnava/mailgen/commit/1de7394a4ad13b0067c049e37d69d1e2f4f88882, and published to `npm` in `2.0.9`. 💯
