### ISSUE TITLE
How to customize CSS template

### ISSUE THREAD

**Issue by Kikobeats** [eladnava/mailgen#33]
Hello,

I love this project, it's so simple and it reduces a lot the quantity of time I need to setup emails in any of my projects. Thanks 👏.

Although templates provided are enough, sometimes I need to customize it in order to fit with my project style in terms of colors.

For example, maybe the template is using `background: #fff` but I need to use `background: #c9c9c9`.

That's nothing mean necessary to create another new template just to replace a color.

Do you think we can establish a mechanism to pass a custom css stylesheet?

I saw that right know CSS is inside HTML and the way to load it is:

```js
var mailGenerator = new Mailgen({
    theme: {
        // Build an absolute path to the theme file within your project
        path: path.resolve('assets/mailgen/theme.html'),
        // Also (optionally) provide the path to a plaintext version of the theme (if you wish to use `generatePlaintext()`)
        plaintextPath: path.resolve('assets/mailgen/theme.txt')
    },
    // Configure your product as usual (see examples above)
    product: {}
});
```

why not separate it into a different thing, making easy reuse HTML structure but passing custom CSS:

```js
var mailGenerator = new Mailgen({
    theme: {
        indexPath: path.resolve('assets/mailgen/theme.html'),
        stylePath: path.resolve('assets/mailgen/theme.css'),
        plaintextPath: path.resolve('assets/mailgen/theme.txt')
    },
    // Configure your product as usual (see examples above)
    product: {}
});
```

Thoughts?

**Comment by eladnava** [comment]
Hi @Kikobeats,
Thanks so much for your kind words and suggestion! 👍 

It would be nice if we could split up the HTML and CSS files. However, HTML e-mails don't really let us do this as we can't reference external CSS files in HTML e-mails. 

CSS must be declared in-line, specifically within the `<head>` tag of the `HTML` email:

```
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <style type="text/css" rel="stylesheet" media="all">
...
...
...
  </style>
```

Separating the HTML and CSS would introduce an issue as the CSS must be in-line in the HTML file. One way to work around it is to include a placeholder e.g. `<!-- CSS GOES HERE -->` that gets replaced at theme parsing time but we have to think about the downsides against the benefit of doing this.

Is it really that inconvenient to edit one HTML file which includes CSS when you want to customize the theme?

**Comment by Kikobeats** [comment]
could be more or less easy to insert inside the HTML using a AST library, although I understand it more easier just copy/paste original template and make your changes 😛
