### ISSUE TITLE
feature request: tabular data

### ISSUE THREAD

**Issue by blackdynamo** [eladnava/mailgen#4]
Would be nice to also have some way to produce tabular data. Labels on the top or left. Maybe pass in an array of data and it builds the table for you.

**Comment by eladnava** [comment]
Hi @blackdynamo, and thanks for the wonderful suggestion!

I've added a `table` element that can be injected into templates, check out the docs for this:https://github.com/eladnava/mailgen#receipt-e-mail

**Comment by blackdynamo** [comment]
@eladnava Nice work. Looks good.

**Comment by eladnava** [comment]
@blackdynamo Thanks mate!
