### ISSUE TITLE
Action button -- alignment option in default theme?

### ISSUE THREAD

**Issue by w4-jake** [eladnava/mailgen#40]
Hi there and thank you for your work on mailgen -- it's been very easy to use.

The 'default' theme is nearly perfect for a project I'm working on, but I would like the button in the action section to be aligned left, just like the text. 

It seems that besides 'color', 'text', and 'link', there isn't an option such as 'alignment' that I can give to 'button' in the email body object:

```
var email = {
    body: {
        name: '...',
        intro: '...',
        action: {
            instructions: '...',
            button: {
                color: '#22BC66',
                text: 'Button text',
                link: 'https://...',
                alignment: 'left' // currently not supported
            }
        },
        outro: '...'
    }
};
```

Is my best option here to make a custom theme nearly identical to the default template, but just change the button formatting according to what I need? Definitely not a major issue to do this, but I just wanted to check that currently this would be the recommended approach and that there is no feature in the works for a button alignment option. Thanks!

**Comment by eladnava** [comment]
Hi @w4-jake,
Thanks so much for your kind feedback!

Indeed, in all built-in `mailgen` themes, the action button is hard-coded to be aligned in the center. There isn't an option currently to customize this. There are two possible ways to provide this functionality:

1) Submit a PR that adds an `alignment` or `align` property to the `action.button` property being passed to `mailgen` (as you suggested), which the HTML templates then check and use to align the button accordingly

2) Modify the `default` theme, changing the button alignment, and using a custom theme with `mailgen`.

Option #2 would definitely take less time, while Option #1 will make this feature accessible for anyone. There doesn't seem to be much demand for this as I haven't heard it as feedback from other users yet, but who knows. Up to you 😄

**Comment by w4-jake** [comment]
Hi @eladnava, 

So sorry for neglecting to get back on this issue! As it happened, center alignment actually became acceptable for the specific content I was making, so any short-term need to carry out either option 1 or 2 went away. 
 
Thank you anyway, though, for your thorough review of the problem(?) and its solutions. Maybe down the road I (or anybody else with a need for this feature) could try Option 1 for fun 😀  Take care!
