### ISSUE TITLE
JSON Schema for mailgen format available?

### ISSUE THREAD

**Issue by svdoever** [eladnava/mailgen#44]
I write mail templates in JSON for mailgen, but would like to provide a JSON schema to do so.
Anyone aware of the existence of a JSON schema for mailgen?

**Comment by eladnava** [comment]
Hi @svdoever,
By JSON schema, do you mean a reference of all the available JSON properties `mailgen` accepts into the `new Mailgen().generate()` function? In that case, check out the "Elements" section in the README:
https://github.com/eladnava/mailgen#elements

**Comment by eladnava** [comment]
Closing due to lack of response, feel free to comment again if you need any further assistance.
