### ISSUE TITLE
How to embed Images

### ISSUE THREAD

**Issue by hiteshsubnani0128** [eladnava/mailgen#45]
I am trying to add images, also it will be great if you can help me with adding social media logos in the footer section. Also I have added the Url of the logo but it is not showing are there any set of rules ( Like logo should be png or of any particular size ).

Regards

**Comment by eladnava** [comment]
Hi @hiteshsubnani0128,
There isn't any documented or intended way to add images to the footer / copyright section. However, a possible workaround is to simply include the HTML `<img>` tag in the `copyright` property, when initializing `Mailgen()`, as follows:

```
// Configure mailgen
var mailGenerator = new Mailgen({
    theme: 'salted',
    product: {
        name: 'Mailgen',
        link: 'https://mailgen.js/',
        // Custom copyright notice
        copyright: 'Copyright © 2016 Mailgen. All rights reserved.<br /><a href="https://facebook.com/js"><img src="https://example.js/img/facebook.png" /></a>',
    }
});
```
