### ISSUE TITLE
Missing typescript definition for Product.logoHeigth

### ISSUE THREAD

**Issue by grzegorzkawkaosik** [eladnava/mailgen#48]
Hello,
There is a missing definition for Product.logoHeight in @types. I have submitted a PR for it in definatelyTyped repository, please check. This is my first contribution ever to such big repository, so it might not be great.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53345

Best Regards,
Greg

**Comment by eladnava** [comment]
Hi @grzegorzkawkaosik,
Looks great to me! 👍  

We will have to wait for the DefinitelyTyped team to review and merge your PR. Cheers for your contribution!
