### ISSUE TITLE
Add 'one click' actions to email subject lines

### ISSUE THREAD

**Issue by CyberFerret** [eladnava/mailgen#5]
Incorporate the Gmail schemas to allow users to perform 'one click' tasks such as confirm a subscription or unsubscribe from a list etc.

Published Google documentation for these schemas and functionality are at: https://developers.google.com/gmail/markup/reference/one-click-action

**Comment by eladnava** [comment]
Hi @CyberFerret, what an excellent suggestion!

I read up on the One Click Actions, and it seems these are more for *one-time* interaction. What happens under the hood is that Gmail will execute an HTTP request on behalf of the user to the target confirmation URL, so this only makes sense for "Confirm your account" transactional mail.

However, I then found [Go-To Actions](https://developers.google.com/gmail/markup/reference/go-to-action).

> Go-To Actions take the user to your website where the action can be completed. Unlike One Click Actions, go-to actions can be interacted with multiple times.

![actions-go-to-action](https://cloud.githubusercontent.com/assets/4394189/15603831/b1cf39f2-2405-11e6-9a94-851600bfb92a.png)

I think we should go with implementing Go-To Actions, specifically, [ViewAction](https://developers.google.com/gmail/markup/reference/go-to-action#view_action).

What do you think about this?

**Comment by SJTreadway** [comment]
Personally I think the ViewAction should definitely be included for tracking purchases via the "successful purchase" email.

**Comment by eladnava** [comment]
@SJTreadway Can you please elaborate?

ViewAction simply adds a button to Gmail's UI with custom text linking to a URL of your choice.

**Comment by eladnava** [comment]
@CyberFerret @SJTreadway It's ready.

You can make use of Gmail's [Go-To Actions](https://developers.google.com/gmail/markup/reference/go-to-action) within your e-mails by suppling the `goToAction` object as follows:

```js
var email = {
    body: {
        // Optionally configure a Go-To Action button 
        goToAction: {
            text: 'Go to Dashboard',
            link: 'https://mailgen.com/confirm?s=d9729feb74992cc3482b350163a1a010',
            description: 'Check the status of your order in your dashboard'
        }
    }
};
```

However, note that you need to [get your sender address whitelisted](https://developers.google.com/gmail/markup/registering-with-google) before your Go-To Actions will show up in Gmail.
