### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by bjrmatos** [eladnava/mailgen#7]
it would be really cool to add i18n support, i'm from Perú where we need to send emails in spanish, right now we are customizing the template to achieve that but it would be really great to have i18n support backed in the library itself.

how would you like to implement this? i can work on it if you like but i want to discuss the details first.

i was thinking that creating a `i18n` folder inside each theme would be a nice approach, inside the `i18n` folder would be a json file for each language, inside the template files (.html, .txt) we would need to use that content depending of the language chosen by the consumer.

<img width="199" alt="captura de pantalla 2016-06-02 a las 12 18 45 p m" src="https://cloud.githubusercontent.com/assets/4262050/15754127/514e7eba-28bc-11e6-9ab4-0872da0b5c31.png">

we would need to create a new option in the `MailGen` constructor, something like `lang`, of course if this option is not specified it will default to `en`.

what do you think?

**Comment by eladnava** [comment]
Hi @bjrmatos,
What an excellent suggestion!

Currently, the only phrases/words that need to be localized are:

* "Hi {name}"
* "Yours truly"
* "All rights reserved"

I'm thinking it would be better if we would make it possible to let users override these phrases with their own, thereby also making it possible to localize them, as well as customize the English ones (some companies wouldn't want to end their e-mails with "Yours truly" for example). 

So what I'm thinking is the following for overriding the copyright:
```
// Configure mailgen by setting a theme and your product info
var mailGenerator = new Mailgen({
    theme: 'default',
    product: {
        name: 'Mailgen',
        // Optional override theme's copyright notice
        copyright: '(C) 2016 Mailgen.js'
    }
});
```

And this is how you would override the rest:

```
var email = {
    body: {
        greeting: 'Dear', // Optionally override 'Hi'
        name: 'John Appleseed',
        intro: 'Welcome to Mailgen! We’re very excited to have you on board.',
        outro: 'Need help, or have questions? Just reply to this email, we\'d love to help.',
        signature: 'Sincerely' // Optionally override 'Yours truly'
    }
};
```

This way, you can both customize and internationalize these static phrases in the templates.

What do you think @bjrmatos?

**Comment by bjrmatos** [comment]
> I'm thinking it would be better if we would make it possible to let users override these phrases with their own, thereby also making it possible to localize them, as well as customize the English ones (some companies wouldn't want to end their e-mails with "Yours truly" for example).
> 
> I think it would simply be harder to internationalize each Mailgen theme into 20+ languages and would allow for less flexibility in the end.

yes, you're right it'll be harder with more themes, your approach sounds better to me 😄 

in the case of new themes, each theme will need to define the custom properties that will allow override the phrases, right? sounds really good to me!

**Comment by eladnava** [comment]
@bjrmatos Yep! I'm thinking of simply adding new variables that will be available to the themes, e.g. `product.copyright`, `greeting`, and `signature`, which can be overridden with user-supplied phrases.

These variables will fallback to the current English phrases if not supplied.

**Comment by eladnava** [comment]
@bjrmatos Let me know if you'd like to work on this yourself, and if not, I'd be glad to do it as well.

**Comment by bjrmatos** [comment]
@eladnava great! unfortunately i only have time on weekends, if you have time to implement this please do! if not i will take care of this in the coming weekend 👍

**Comment by eladnava** [comment]
@bjrmatos No problem! Found some time and implemented this:
https://github.com/eladnava/mailgen#language-customizations

Thanks again for your suggestion! =)

**Comment by bjrmatos** [comment]
you're awesome! :heart:
