### ISSUE TITLE
Having buttons inside of tables

### ISSUE THREAD

**Issue by Epichris360** [eladnava/mailgen#71]
Hi mailgen team,  I looked through the code and didn't see anything that allows you to add buttons to tables, in our use case we need to add links to individual items in the table. 

Is something like this currently doable ? and I just haven't figured it out?

**Comment by eladnava** [comment]
Hi @Epichris360,
Thanks for creating this issue.

There is currently no button functionality inside table rows/cells. However, you could simply inject HTML buttons into tables as follows:

```
var email = {
    body: {
        table: {
            data: [
                {
                    item: 'Mailgen',
                    description: 'Programmatically create beautiful e-mails using plain old JavaScript.',
                    link: '<div style="...">Button</div>'
                }
            ]
        }
    }
};
```
Apologies for the lack of a built-in solution, but it isn't a highly-requested feature at this time.

**Comment by Epichris360** [comment]
Thanks!
