### ISSUE TITLE
greeting: false, // not working

### ISSUE THREAD

**Issue by Save5Bucks** [eladnava/mailgen#73]
Great work on this by the way! 

Setting the greeting to false doesn't remove the greeting. I tried to change it and it is not working either.

**Comment by Save5Bucks** [comment]
var email = {
        body: {
        greeting: false,
        signature: false,
            //name: 'CORE CONSTRUCTION',
            intro: 'YOU HAVE A NEW TRADE APPLICATION',
            action: {
                instructions: 'TO SEE THIS APPLICATION CLICK THE LINK BELOW:',
                button: {
                    color: '#22BC66', // Optional action button color
                    text: 'CORE TOOLS',
                    link: 'https://google.com'
                }
            },
            outro: 'IF YOU ARE HAVING PROBLEMS PLEASE CONTACT THE SYSTEM ADMIN.'
        }

**Comment by eladnava** [comment]
Hi @Save5Bucks,
Thanks for your kind words!

As per the issue - I can't reproduce - here's a screenshot of the output when running `mailgen` with the above code:

![Screen Shot 2023-01-20 at 11 18 15 AM](https://user-images.githubusercontent.com/4394189/213749751-8222a064-896d-4c5e-a07e-10cc99788e22.png)

As you can see, the greeting & title is gone. Please ensure you are using the latest `mailgen` (`2.0.27`).
