### ISSUE TITLE
add {year}

### ISSUE THREAD

**Issue by Kikobeats** [eladnava/mailgen#76]
Hello and congrats for this project; I'm using it as part of https://tom.js.org/ for years 🙂

I noted all my emails footer copyright is outdated because I forgot to update the year.

For solving this, I added `{year}` as template variable and compile copyright as template before being passed to mailgen:
https://github.com/Kikobeats/tom/pull/270/files#diff-23bf7f84d90195c1f1898d71fc67d20dfd65fa80f9fec24e3e624f552399eb9cR29

I thought that maybe you would to add support for this as parf of the codebase, it could be a simple and great feature.

**Comment by eladnava** [comment]
Hi @Kikobeats,
Thanks so much for your kind words!

The library already populates the current year in the copyright in case you don't override the default copyright:
https://github.com/eladnava/mailgen/blob/a9b249606882c5145553f76065174f5e66af6156/index.js#L27 

And in case you override the copyright, I've gone forth and updated the README example to include automatic year display in https://github.com/eladnava/mailgen/commit/3096b0c379ec565b6b0cd3c2033e04cf142bbdd4.

**Comment by Kikobeats** [comment]
that's great; I lose the point due the fact I'm using YAML files for defining the email, but yea it seems I don't need another template for this, thanks for replying!
